global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'jenkins'
    metrics_path: /prometheus
    static_configs:
      - targets: ['172.17.0.1:8080']

  - job_name: 'app-timesheet'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['app-timesheet:8089']
